# Etapa 1: Construir el Frontend
FROM node:16 AS frontend-builder
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build

# Etapa 2: Configurar el Contenedor Final
FROM node:16
WORKDIR /app/frontend

# Copiar el frontend construido desde la etapa 1
COPY --from=frontend-builder /app/frontend ./

# Exponer el puerto que la aplicación utilizará
EXPOSE 3001

# Comando para ejecutar el frontend
CMD ["npm", "start"]
