name: deploy-backend

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.backend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp-backend:latest

    - name: Debug build failure
      run: |
        docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/epdmb-backend:latest /bin/sh -c "ls -la /app/backend && npm run build"
